# $Simulation$

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import viz # curriculum example visualizations

np.random.seed(9)

### 1. How likely is it that you roll doubles when rolling two dice?

In [14]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[1, 1],
       [6, 5],
       [2, 6],
       ...,
       [6, 6],
       [5, 5],
       [4, 1]])

In [34]:
df = pd.DataFrame(rolls, columns=['roll_1', 'roll_2'])
df.shape

(10000, 2)

In [27]:
bool_mask = df.roll_1.values == df.roll_2.values

In [37]:
bool_mask.sum()/bool_mask.size

0.1636

In [54]:
#probability of rolling double dice
bool_mask.mean()

0.1636

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?


In [42]:
n_trials = nrows = 10_000
n_coins = ncols = 8

# 1 equals heads 0 equals tails
flips = np.random.choice([0, 1], size = (n_trials, n_coins))
flips

array([[1, 0, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 1]])

In [47]:
flips_df = pd.DataFrame(flips, columns=['1st','2nd','3rd','4th','5th','6th','7th','8th'])
flips_df.head()

1st  2nd  3rd  4th  5th  6th  7th  8th
0    1    0    0    1    1    1    1    1
1    1    0    1    0    0    0    1    1
2    1    0    1    0    0    0    1    1
3    0    0    0    1    0    1    1    0
4    1    0    1    1    0    1    0    1

In [50]:
total_heads= flips_df.sum(axis=1)
total_heads.head()

0    6
1    4
2    4
3    3
4    5
dtype: int64

In [52]:
# probability of getting 3 heads
(total_heads ==3).mean()

0.2188

In [55]:
#probablity of getting more than 3 heads
(total_heads > 3).mean()

0.6337

### 3. There are approximately 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?


In [81]:
n_trials = nrows = 10_000
n_students = ncols = 2

# 0 = Web Development students, 1=Data Science students
billboard = np.random.choice([0,0,0,1], size = (n_trials, n_students))


In [86]:
billboard_df = pd.DataFrame(billboard, columns=['1st','2nd'])
billboard_df.tail()

1st  2nd
9995    0    1
9996    0    0
9997    1    0
9998    0    0
9999    1    0

In [95]:
# probability of two data science students selected on a billboard
((billboard_df.sum(axis=1) == 2).sum())/len(billboard_df)


0.0643

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values.


In [145]:
nrows = 10_000
monday = 17

array_pop = np.random.normal(loc = 3 , scale = 1.5, size=(nrows,5))

In [147]:
# Monday Tuesday  Wednesday  Thursday
sum_pop= array_pop.sum(axis=1)

In [148]:
sum_pop

array([13.88757223,  8.16134546, 16.62591946, ..., 17.76262174,
       11.8781606 ,  9.75049894])

In [158]:
bool_mask = sum_pop < 17
                   
                      

In [161]:
bool_mask.sum()/len(bool_mask)

0.7259

In [162]:
# probability that I will be able to buy poptarts on Friday
bool_mask.mean()

0.7259

### 5. Compare Heights
* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* Since you have means and standard deviations, you can use np.random.normal to generate observations.
* If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [165]:
nrows = 10_000
men_random = np.random.normal(loc = 178, scale =8, size = (nrows,1))
men_random

array([[190.88796959],
       [166.17563607],
       [182.30292171],
       ...,
       [172.9158126 ],
       [174.19909036],
       [183.81536539]])

In [185]:
women_random = np.random.normal(loc = 170, scale =6, size = (nrows,1))
women_random

array([[173.03255568],
       [169.48935079],
       [170.69102706],
       ...,
       [166.02061306],
       [177.42393796],
       [175.90773415]])

In [187]:
array_no = np.array([men_random, women_random])

array_no

array([[[190.88796959],
        [166.17563607],
        [182.30292171],
        ...,
        [172.9158126 ],
        [174.19909036],
        [183.81536539]],

       [[173.03255568],
        [169.48935079],
        [170.69102706],
        ...,
        [166.02061306],
        [177.42393796],
        [175.90773415]]])

SyntaxError: invalid syntax (959771982.py, line 1)

In [189]:
men_women= np.array(list(zip(men_random,women_random)))

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.

* What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
* What is the probability that we observe an installation issue within the first 150 students that download anaconda?
* How likely is it that 450 students all download anaconda without an issue?


### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
* However, you haven't seen a food truck there in 3 days. How unlikely is this?
* How likely is it that a food truck will show up sometime this week?

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?